[package]
name = "rweblet"
version = "0.1.0"
authors = ["Simon Hoxer Bønding <sinb-dev@techcollege.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
